import { defineConfig } from 'orval'

export default defineConfig({
  api: {
    input: {
      target:
        process.env.OPENAPI_URL ??
        '../mini_staffomatic_api/public/v1/openapi.json',
      override: {
        transformer: (options) => {
          // Remove '/v1/{account_subdomain}' from paths so the subdomain
          // is injected centrally in auth-fetch.ts rather than per-hook.
          const paths = Object.fromEntries(
            Object.entries(options.paths).map(([key, value]) => [
              key.replace('/v1/{account_subdomain}', ''),
              {
                ...value,
                parameters: value.parameters?.filter((param) =>
                  'name' in param ? param.name !== 'account_subdomain' : true,
                ),
              },
            ]),
          )

          return { ...options, paths }
        },
      },
    },
    output: {
      clean: true,
      mode: 'tags-split',
      target: './src/generated/api/',
      client: 'react-query',
      schemas: './src/generated/schemas',
      httpClient: 'fetch',
      override: {
        header: () => ['Generated by orval', 'Do not edit manually.'],
        mutator: {
          path: './src/lib/auth-fetch.ts',
          name: 'authFetch',
        },
        query: {
          useSuspenseQuery: true,
        },
        fetch: {
          includeHttpResponseReturnType: false,
        },
      },
    },
    hooks: {
      afterAllFilesWrite: 'prettier --write',
    },
  },
})
