/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedShiftsIndexRouteImport } from './routes/_authenticated/shifts/index'
import { Route as AuthenticatedSchedulesIndexRouteImport } from './routes/_authenticated/schedules/index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedShiftsShiftIdRouteImport } from './routes/_authenticated/shifts/$shiftId'
import { Route as AuthenticatedSchedulesScheduleIdRouteImport } from './routes/_authenticated/schedules/$scheduleId'
import { Route as AuthenticatedApplicationsApplicationIdRouteImport } from './routes/_authenticated/applications/$applicationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedShiftsIndexRoute =
  AuthenticatedShiftsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShiftsRoute,
  } as any)
const AuthenticatedSchedulesIndexRoute =
  AuthenticatedSchedulesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSchedulesRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedShiftsShiftIdRoute =
  AuthenticatedShiftsShiftIdRouteImport.update({
    id: '/$shiftId',
    path: '/$shiftId',
    getParentRoute: () => AuthenticatedShiftsRoute,
  } as any)
const AuthenticatedSchedulesScheduleIdRoute =
  AuthenticatedSchedulesScheduleIdRouteImport.update({
    id: '/$scheduleId',
    path: '/$scheduleId',
    getParentRoute: () => AuthenticatedSchedulesRoute,
  } as any)
const AuthenticatedApplicationsApplicationIdRoute =
  AuthenticatedApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/schedules': typeof AuthenticatedSchedulesRouteWithChildren
  '/shifts': typeof AuthenticatedShiftsRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/schedules/$scheduleId': typeof AuthenticatedSchedulesScheduleIdRoute
  '/shifts/$shiftId': typeof AuthenticatedShiftsShiftIdRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/schedules/': typeof AuthenticatedSchedulesIndexRoute
  '/shifts/': typeof AuthenticatedShiftsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/schedules/$scheduleId': typeof AuthenticatedSchedulesScheduleIdRoute
  '/shifts/$shiftId': typeof AuthenticatedShiftsShiftIdRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/schedules': typeof AuthenticatedSchedulesIndexRoute
  '/shifts': typeof AuthenticatedShiftsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRouteWithChildren
  '/_authenticated/shifts': typeof AuthenticatedShiftsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/_authenticated/schedules/$scheduleId': typeof AuthenticatedSchedulesScheduleIdRoute
  '/_authenticated/shifts/$shiftId': typeof AuthenticatedShiftsShiftIdRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/schedules/': typeof AuthenticatedSchedulesIndexRoute
  '/_authenticated/shifts/': typeof AuthenticatedShiftsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/applications'
    | '/profile'
    | '/schedules'
    | '/shifts'
    | '/users'
    | '/applications/$applicationId'
    | '/schedules/$scheduleId'
    | '/shifts/$shiftId'
    | '/users/$userId'
    | '/applications/'
    | '/schedules/'
    | '/shifts/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/profile'
    | '/applications/$applicationId'
    | '/schedules/$scheduleId'
    | '/shifts/$shiftId'
    | '/users/$userId'
    | '/applications'
    | '/schedules'
    | '/shifts'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/applications'
    | '/_authenticated/profile'
    | '/_authenticated/schedules'
    | '/_authenticated/shifts'
    | '/_authenticated/users'
    | '/_authenticated/applications/$applicationId'
    | '/_authenticated/schedules/$scheduleId'
    | '/_authenticated/shifts/$shiftId'
    | '/_authenticated/users/$userId'
    | '/_authenticated/applications/'
    | '/_authenticated/schedules/'
    | '/_authenticated/shifts/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/shifts/': {
      id: '/_authenticated/shifts/'
      path: '/'
      fullPath: '/shifts/'
      preLoaderRoute: typeof AuthenticatedShiftsIndexRouteImport
      parentRoute: typeof AuthenticatedShiftsRoute
    }
    '/_authenticated/schedules/': {
      id: '/_authenticated/schedules/'
      path: '/'
      fullPath: '/schedules/'
      preLoaderRoute: typeof AuthenticatedSchedulesIndexRouteImport
      parentRoute: typeof AuthenticatedSchedulesRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/shifts/$shiftId': {
      id: '/_authenticated/shifts/$shiftId'
      path: '/$shiftId'
      fullPath: '/shifts/$shiftId'
      preLoaderRoute: typeof AuthenticatedShiftsShiftIdRouteImport
      parentRoute: typeof AuthenticatedShiftsRoute
    }
    '/_authenticated/schedules/$scheduleId': {
      id: '/_authenticated/schedules/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/schedules/$scheduleId'
      preLoaderRoute: typeof AuthenticatedSchedulesScheduleIdRouteImport
      parentRoute: typeof AuthenticatedSchedulesRoute
    }
    '/_authenticated/applications/$applicationId': {
      id: '/_authenticated/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsApplicationIdRoute: typeof AuthenticatedApplicationsApplicationIdRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsApplicationIdRoute:
      AuthenticatedApplicationsApplicationIdRoute,
    AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedSchedulesRouteChildren {
  AuthenticatedSchedulesScheduleIdRoute: typeof AuthenticatedSchedulesScheduleIdRoute
  AuthenticatedSchedulesIndexRoute: typeof AuthenticatedSchedulesIndexRoute
}

const AuthenticatedSchedulesRouteChildren: AuthenticatedSchedulesRouteChildren =
  {
    AuthenticatedSchedulesScheduleIdRoute:
      AuthenticatedSchedulesScheduleIdRoute,
    AuthenticatedSchedulesIndexRoute: AuthenticatedSchedulesIndexRoute,
  }

const AuthenticatedSchedulesRouteWithChildren =
  AuthenticatedSchedulesRoute._addFileChildren(
    AuthenticatedSchedulesRouteChildren,
  )

interface AuthenticatedShiftsRouteChildren {
  AuthenticatedShiftsShiftIdRoute: typeof AuthenticatedShiftsShiftIdRoute
  AuthenticatedShiftsIndexRoute: typeof AuthenticatedShiftsIndexRoute
}

const AuthenticatedShiftsRouteChildren: AuthenticatedShiftsRouteChildren = {
  AuthenticatedShiftsShiftIdRoute: AuthenticatedShiftsShiftIdRoute,
  AuthenticatedShiftsIndexRoute: AuthenticatedShiftsIndexRoute,
}

const AuthenticatedShiftsRouteWithChildren =
  AuthenticatedShiftsRoute._addFileChildren(AuthenticatedShiftsRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRouteWithChildren
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRouteWithChildren,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
